/*
 * Created on 2023-09-26 ( 11:48:49 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package duan.travel.entities;

import java.io.Serializable;
import java.util.List;
import jakarta.persistence.*;

/**
 * JPA entity class for "Account"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="account", catalog="travellaw" )
public class Account implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id ;

    //--- ENTITY DATA FIELDS 
    @Column(name="username", nullable=false, length=16)
    private String     username ;

    @Column(name="password", nullable=false, length=16)
    private String     password ;

    @Column(name="phone", length=12)
    private String     phone ;

    @Column(name="email", nullable=false, length=100)
    private String     email ;

    @Column(name="firstname", nullable=false, length=100)
    private String     firstname ;

    @Column(name="lastname", nullable=false, length=100)
    private String     lastname ;

    @Column(name="address", length=200)
    private String     address ;

    @Column(name="avatar", length=100)
    private String     avatar ;

    @Column(name="status", nullable=false)
    private Boolean    status ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @OneToMany(mappedBy="account")
    private List<Authorized> listOfAuthorized ; 

    @OneToMany(mappedBy="account")
    private List<Commentblog> listOfCommentblog ; 

    @OneToMany(mappedBy="account")
    private List<Favorite> listOfFavorite ; 


    /**
     * Constructor
     */
    public Account() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    public void setUsername( String username ) {
        this.username = username ;
    }
    public String getUsername() {
        return this.username;
    }

    public void setPassword( String password ) {
        this.password = password ;
    }
    public String getPassword() {
        return this.password;
    }

    public void setPhone( String phone ) {
        this.phone = phone ;
    }
    public String getPhone() {
        return this.phone;
    }

    public void setEmail( String email ) {
        this.email = email ;
    }
    public String getEmail() {
        return this.email;
    }

    public void setFirstname( String firstname ) {
        this.firstname = firstname ;
    }
    public String getFirstname() {
        return this.firstname;
    }

    public void setLastname( String lastname ) {
        this.lastname = lastname ;
    }
    public String getLastname() {
        return this.lastname;
    }

    public void setAddress( String address ) {
        this.address = address ;
    }
    public String getAddress() {
        return this.address;
    }

    public void setAvatar( String avatar ) {
        this.avatar = avatar ;
    }
    public String getAvatar() {
        return this.avatar;
    }

    public void setStatus( Boolean status ) {
        this.status = status ;
    }
    public Boolean getStatus() {
        return this.status;
    }

    //--- GETTERS FOR LINKS
    public List<Authorized> getListOfAuthorized() {
        return this.listOfAuthorized;
    } 

    public List<Commentblog> getListOfCommentblog() {
        return this.listOfCommentblog;
    } 

    public List<Favorite> getListOfFavorite() {
        return this.listOfFavorite;
    } 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(id);
        sb.append("|");
        sb.append(username);
        sb.append("|");
        sb.append(password);
        sb.append("|");
        sb.append(phone);
        sb.append("|");
        sb.append(email);
        sb.append("|");
        sb.append(firstname);
        sb.append("|");
        sb.append(lastname);
        sb.append("|");
        sb.append(address);
        sb.append("|");
        sb.append(avatar);
        sb.append("|");
        sb.append(status);
        return sb.toString(); 
    } 

}
