/*
 * Created on 2023-09-26 ( 11:48:49 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package duan.travel.entities;

import java.io.Serializable;
import jakarta.persistence.*;

/**
 * JPA entity class for "Authorized"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="authorized", catalog="travellaw" )
public class Authorized implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id ;

    //--- ENTITY DATA FIELDS 
    @Column(name="account_id", nullable=false)
    private Integer    accountId ;

    @Column(name="role_id", nullable=false)
    private Integer    roleId ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JoinColumn(name="role_id", referencedColumnName="id", insertable=false, updatable=false)
    private Role       role ; 

    @ManyToOne
    @JoinColumn(name="account_id", referencedColumnName="id", insertable=false, updatable=false)
    private Account    account ; 


    /**
     * Constructor
     */
    public Authorized() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    public void setAccountId( Integer accountId ) {
        this.accountId = accountId ;
    }
    public Integer getAccountId() {
        return this.accountId;
    }

    public void setRoleId( Integer roleId ) {
        this.roleId = roleId ;
    }
    public Integer getRoleId() {
        return this.roleId;
    }

    //--- GETTERS FOR LINKS
    public Role getRole() {
        return this.role;
    } 

    public Account getAccount() {
        return this.account;
    } 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(id);
        sb.append("|");
        sb.append(accountId);
        sb.append("|");
        sb.append(roleId);
        return sb.toString(); 
    } 

}
