/*
 * Created on 2023-09-26 ( 11:48:49 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package duan.travel.entities;

import java.io.Serializable;
import java.util.Date;
import java.util.List;
import jakarta.persistence.*;

/**
 * JPA entity class for "Blog"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="blog", catalog="travellaw" )
public class Blog implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id ;

    //--- ENTITY DATA FIELDS 
    @Column(name="category_id", nullable=false)
    private Integer    categoryId ;

    @Column(name="title", nullable=false, length=50)
    private String     title ;

    @Column(name="image", nullable=false, length=100)
    private String     image ;

    @Column(name="descrription", length=65535)
    private String     descrription ;

    @Column(name="status", nullable=false)
    private Boolean    status ;

    @Temporal(TemporalType.DATE)
    @Column(name="create_date", nullable=false)
    private Date       createDate ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @OneToMany(mappedBy="blog")
    private List<Favorite> listOfFavorite ; 

    @OneToMany(mappedBy="blog")
    private List<Commentblog> listOfCommentblog ; 

    @ManyToOne
    @JoinColumn(name="category_id", referencedColumnName="id", insertable=false, updatable=false)
    private Category   category ; 


    /**
     * Constructor
     */
    public Blog() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    public void setCategoryId( Integer categoryId ) {
        this.categoryId = categoryId ;
    }
    public Integer getCategoryId() {
        return this.categoryId;
    }

    public void setTitle( String title ) {
        this.title = title ;
    }
    public String getTitle() {
        return this.title;
    }

    public void setImage( String image ) {
        this.image = image ;
    }
    public String getImage() {
        return this.image;
    }

    public void setDescrription( String descrription ) {
        this.descrription = descrription ;
    }
    public String getDescrription() {
        return this.descrription;
    }

    public void setStatus( Boolean status ) {
        this.status = status ;
    }
    public Boolean getStatus() {
        return this.status;
    }

    public void setCreateDate( Date createDate ) {
        this.createDate = createDate ;
    }
    public Date getCreateDate() {
        return this.createDate;
    }

    //--- GETTERS FOR LINKS
    public List<Favorite> getListOfFavorite() {
        return this.listOfFavorite;
    } 

    public List<Commentblog> getListOfCommentblog() {
        return this.listOfCommentblog;
    } 

    public Category getCategory() {
        return this.category;
    } 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(id);
        sb.append("|");
        sb.append(categoryId);
        sb.append("|");
        sb.append(title);
        sb.append("|");
        sb.append(image);
        // attribute 'descrription' not usable (type = String Long Text)
        sb.append("|");
        sb.append(status);
        sb.append("|");
        sb.append(createDate);
        return sb.toString(); 
    } 

}
