/*
 * Created on 2023-09-26 ( 11:48:49 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package duan.travel.entities;

import java.io.Serializable;
import java.util.Date;
import jakarta.persistence.*;

/**
 * JPA entity class for "Commentblog"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="commentblog", catalog="travellaw" )
public class Commentblog implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id ;

    //--- ENTITY DATA FIELDS 
    @Column(name="blog_id", nullable=false)
    private Integer    blogId ;

    @Column(name="account_id", nullable=false)
    private Integer    accountId ;

    @Column(name="status", nullable=false)
    private Boolean    status ;

    @Column(name="title", nullable=false, length=100)
    private String     title ;

    @Temporal(TemporalType.DATE)
    @Column(name="create_date", nullable=false)
    private Date       createDate ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JoinColumn(name="blog_id", referencedColumnName="id", insertable=false, updatable=false)
    private Blog       blog ; 

    @ManyToOne
    @JoinColumn(name="account_id", referencedColumnName="id", insertable=false, updatable=false)
    private Account    account ; 


    /**
     * Constructor
     */
    public Commentblog() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    public void setBlogId( Integer blogId ) {
        this.blogId = blogId ;
    }
    public Integer getBlogId() {
        return this.blogId;
    }

    public void setAccountId( Integer accountId ) {
        this.accountId = accountId ;
    }
    public Integer getAccountId() {
        return this.accountId;
    }

    public void setStatus( Boolean status ) {
        this.status = status ;
    }
    public Boolean getStatus() {
        return this.status;
    }

    public void setTitle( String title ) {
        this.title = title ;
    }
    public String getTitle() {
        return this.title;
    }

    public void setCreateDate( Date createDate ) {
        this.createDate = createDate ;
    }
    public Date getCreateDate() {
        return this.createDate;
    }

    //--- GETTERS FOR LINKS
    public Blog getBlog() {
        return this.blog;
    } 

    public Account getAccount() {
        return this.account;
    } 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(id);
        sb.append("|");
        sb.append(blogId);
        sb.append("|");
        sb.append(accountId);
        sb.append("|");
        sb.append(status);
        sb.append("|");
        sb.append(title);
        sb.append("|");
        sb.append(createDate);
        return sb.toString(); 
    } 

}
