/*
 * Created on 2023-09-26 ( 11:48:49 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package duan.travel.entities;

import java.io.Serializable;
import jakarta.persistence.*;

/**
 * JPA entity class for "Favorite"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="favorite", catalog="travellaw" )
public class Favorite implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id ;

    //--- ENTITY DATA FIELDS 
    @Column(name="blog_id", nullable=false)
    private Integer    blogId ;

    @Column(name="account_id", nullable=false)
    private Integer    accountId ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JoinColumn(name="account_id", referencedColumnName="id", insertable=false, updatable=false)
    private Account    account ; 

    @ManyToOne
    @JoinColumn(name="blog_id", referencedColumnName="id", insertable=false, updatable=false)
    private Blog       blog ; 


    /**
     * Constructor
     */
    public Favorite() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    public void setBlogId( Integer blogId ) {
        this.blogId = blogId ;
    }
    public Integer getBlogId() {
        return this.blogId;
    }

    public void setAccountId( Integer accountId ) {
        this.accountId = accountId ;
    }
    public Integer getAccountId() {
        return this.accountId;
    }

    //--- GETTERS FOR LINKS
    public Account getAccount() {
        return this.account;
    } 

    public Blog getBlog() {
        return this.blog;
    } 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(id);
        sb.append("|");
        sb.append(blogId);
        sb.append("|");
        sb.append(accountId);
        return sb.toString(); 
    } 

}
